#!/usr/bin/env python3
"""
Fine-tune YOLOv8 on the HK indoor hazard dataset.

Runs locally — no Colab required. Picks the best available device
(CUDA → MPS for Apple Silicon → CPU).

Usage (typical):
    python3 scripts/train_hazard_yolo.py \
        --data data/hazard.yaml \
        --epochs 50 \
        --imgsz 640

Quick sanity check (1 epoch, 16 imgs):
    python3 scripts/train_hazard_yolo.py --epochs 1 --imgsz 416 --batch 4

Expected dataset layout (Ultralytics format):
    data/HK_custom_for_finetuning/
        images/
            train/*.jpg
            val/*.jpg
        labels/
            train/*.txt   # YOLO format: class_id cx cy w h (normalized)
            val/*.txt
    data/hazard.yaml      # see this script's --init-yaml flag

Class IDs (must match config.HAZARD_PRIORITY ordering):
    0: stairs
    1: glass_door
    2: pillar
    3: hanging_obstacle
    4: low_obstacle
    5: person
"""

import argparse
import os
import sys
import textwrap
from pathlib import Path

# Project root on sys.path so `import config` works
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config  # noqa: E402


# Order matters — used as YOLO class ids (0, 1, 2, ...) in labels/*.txt
HAZARD_CLASS_ORDER = [
    "stairs",
    "glass_door",
    "pillar",
    "hanging_obstacle",
    "low_obstacle",
    "person",
]


DATA_YAML_TEMPLATE = """\
# HK indoor hazard dataset (Ultralytics YOLO format)
# Auto-generated by scripts/train_hazard_yolo.py --init-yaml

path: {dataset_root}
train: images/train
val: images/val

nc: {nc}
names:
{names_block}
"""


def write_data_yaml(yaml_path: str, dataset_root: str) -> None:
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(HAZARD_CLASS_ORDER))
    content = DATA_YAML_TEMPLATE.format(
        dataset_root=dataset_root,
        nc=len(HAZARD_CLASS_ORDER),
        names_block=names_block,
    )
    Path(yaml_path).write_text(content)
    print(f"Wrote dataset YAML: {yaml_path}")


def pick_device() -> str:
    """Pick the best locally available device for YOLO training."""
    try:
        import torch
        if torch.cuda.is_available():
            return "cuda"
        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            return "mps"
    except ImportError:
        pass
    return "cpu"


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv8 on HK hazard data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(__doc__ or ""),
    )
    parser.add_argument(
        "--data", default="data/hazard.yaml",
        help="Path to dataset YAML (Ultralytics format). Default: data/hazard.yaml"
    )
    parser.add_argument(
        "--init-yaml", action="store_true",
        help="Create a starter data/hazard.yaml at --data path and exit."
    )
    parser.add_argument(
        "--dataset-root", default=os.path.join(config.DATA_DIR, "HK_custom_for_finetuning"),
        help="Dataset root containing images/{train,val} and labels/{train,val}."
    )
    parser.add_argument(
        "--weights", default=config.YOLO_MODEL_PATH,
        help="Starting weights (default: project YOLOv8m checkpoint)."
    )
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default=None,
                        help="cuda / mps / cpu / 0,1 — auto-pick if omitted.")
    parser.add_argument("--name", default="hazard_yolov8m",
                        help="Run name (used as runs/detect/<name>/).")
    parser.add_argument("--lr0", type=float, default=0.001,
                        help="Initial learning rate (small for transfer learning).")
    parser.add_argument("--patience", type=int, default=20,
                        help="Early-stop patience (epochs).")
    args = parser.parse_args()

    if args.init_yaml:
        os.makedirs(os.path.dirname(os.path.abspath(args.data)), exist_ok=True)
        write_data_yaml(args.data, args.dataset_root)
        print("\nNext steps:")
        print(f"  1. Place images under   {args.dataset_root}/images/{{train,val}}/")
        print(f"  2. Place YOLO labels    {args.dataset_root}/labels/{{train,val}}/")
        print(f"  3. Run training:        python3 scripts/train_hazard_yolo.py")
        return

    # Lazy import so --init-yaml works without ultralytics installed.
    from ultralytics import YOLO

    device = args.device or pick_device()
    print(f"Device: {device}")
    print(f"Weights: {args.weights}")
    print(f"Data:    {args.data}")
    print(f"Classes: {HAZARD_CLASS_ORDER}")

    model = YOLO(args.weights)
    results = model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=device,
        name=args.name,
        lr0=args.lr0,
        patience=args.patience,
        # Sensible defaults for small dataset transfer learning:
        cos_lr=True,         # cosine LR schedule
        warmup_epochs=3,
        mosaic=1.0,          # keep mosaic aug for small dataset
        close_mosaic=10,     # turn off mosaic in last 10 epochs
        plots=True,
    )
    print(f"Training done. Best weights: {results.save_dir}/weights/best.pt")
    print("To use the fine-tuned model in scene_analyzer, set:")
    print(f"  config.YOLO_MODEL_PATH = '{results.save_dir}/weights/best.pt'")


if __name__ == "__main__":
    main()
