#!/usr/bin/env python3
"""
Fine-tune YOLOv8 on the HK indoor hazard dataset, with three optional knobs:

  --rgbd                  enable RGB-D 4-channel input (variant B)
  --distance-weighted     enable distance-weighted detection loss (variant C)
  --tau FLOAT             scale for distance weight w(d) = exp(-d/tau)  [default 2.0]

Runs locally — no Colab required. Picks the best available device
(CUDA → MPS for Apple Silicon → CPU).

Default class taxonomy comes from scripts/convert_to_yolo.py (8 classes):
    chair, table, refrigerator, door, bed, couch, dining_table, obstacle

Usage examples:
    # A — RGB baseline
    python3 scripts/train_hazard_yolo.py --epochs 100

    # A+C — RGB + distance-weighted loss
    python3 scripts/train_hazard_yolo.py --epochs 100 --distance-weighted

    # A+B+C — RGB-D + distance-weighted loss
    python3 scripts/train_hazard_yolo.py --epochs 100 --rgbd --distance-weighted

    # Sanity check: tau→inf must reproduce A (within rounding)
    python3 scripts/train_hazard_yolo.py --epochs 1 --distance-weighted --tau 1e9

Run from project root.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import textwrap

# Project root on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config  # noqa: E402

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(message)s")


# Class taxonomy is owned by scripts/convert_to_yolo.py; we re-import to stay in sync.
from convert_to_yolo import HAZARD_CLASSES  # noqa: E402


# ============================================================
# Device selection
# ============================================================


def pick_device() -> str:
    try:
        import torch
        if torch.cuda.is_available():
            return "cuda"
        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            return "mps"
    except ImportError:
        pass
    return "cpu"


# ============================================================
# Variant C — distance-weighted loss (lazy attached after model load)
# ============================================================


def attach_distance_weighted_loss(yolo_model, tau: float):
    """
    Replace the model's training criterion with a WeightedV8DetectionLoss.

    Ultralytics builds its loss inside `model.init_criterion()`. We monkey-
    patch that method so the override is picked up the first time training
    needs the loss (lazy — no premature import of ultralytics internals).
    """
    from src.depth_yolo.loss import WeightedV8DetectionLoss

    original_init = yolo_model.model.init_criterion  # bound method

    def _init_with_weights():
        original_init()  # standard build
        yolo_model.model.criterion = WeightedV8DetectionLoss(yolo_model.model, tau=tau)
        return yolo_model.model.criterion

    yolo_model.model.init_criterion = _init_with_weights
    logger.info(f"  Distance-weighted loss attached (tau={tau}).")


# ============================================================
# Variant B — RGB-D first-conv surgery
# ============================================================


def make_rgbd(yolo_model, init: str = "rgb_mean"):
    from src.depth_yolo.model import convert_first_conv_to_rgbd

    convert_first_conv_to_rgbd(yolo_model, init=init)
    logger.warning(
        "  RGB-D first conv installed, but ultralytics' built-in dataloader "
        "still feeds 3-channel RGB. To finish variant B you also need a "
        "dataloader that yields 4-channel tensors — see "
        "src/depth_yolo/dataset.RGBDYoloDataset for the building block."
    )


# ============================================================
# Main
# ============================================================


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv8 on HK hazard data (variants A / A+C / A+B+C)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(__doc__ or ""),
    )
    parser.add_argument(
        "--data",
        default=os.path.join(config.DATA_DIR, "HK_custom_for_finetuning", "data.yaml"),
        help="Ultralytics dataset YAML. Generated by scripts/convert_to_yolo.py.",
    )
    parser.add_argument(
        "--weights", default=config.YOLO_MODEL_PATH,
        help="Starting weights (default: project YOLOv8m checkpoint).",
    )
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--device", default=None,
                        help="cuda / mps / cpu / 0,1 — auto-pick if omitted.")
    parser.add_argument("--name", default=None,
                        help="Run name. Auto-generated from variant flags if omitted.")
    parser.add_argument("--lr0", type=float, default=0.001)
    parser.add_argument("--patience", type=int, default=30)

    # Variant flags
    parser.add_argument("--rgbd", action="store_true",
                        help="(B) Use RGB-D 4-channel first conv (mean-init).")
    parser.add_argument("--rgbd-init", choices=["rgb_mean", "zero", "random"],
                        default="rgb_mean", help="(B) 4th-channel init scheme.")
    parser.add_argument("--distance-weighted", action="store_true",
                        help="(C) Enable distance-weighted detection loss.")
    parser.add_argument("--tau", type=float, default=2.0,
                        help="(C) Scale for w(d) = exp(-d/tau). Default 2.0 m.")
    args = parser.parse_args()

    # Lazy ultralytics
    from ultralytics import YOLO  # noqa: E402  (heavy import)

    device = args.device or pick_device()
    name = args.name or _auto_run_name(args)

    logger.info(f"Device:  {device}")
    logger.info(f"Weights: {args.weights}")
    logger.info(f"Data:    {args.data}")
    logger.info(f"Classes: {HAZARD_CLASSES}")
    logger.info(f"Variant flags: rgbd={args.rgbd}, distance_weighted={args.distance_weighted}, "
                f"tau={args.tau}")

    model = YOLO(args.weights)

    if args.rgbd:
        make_rgbd(model, init=args.rgbd_init)
    if args.distance_weighted:
        attach_distance_weighted_loss(model, tau=args.tau)

    results = model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=device,
        name=name,
        lr0=args.lr0,
        patience=args.patience,
        # Augmentation (kept aggressive — small dataset)
        cos_lr=True,
        warmup_epochs=3,
        mosaic=1.0,
        mixup=0.1,
        hsv_v=0.4,
        fliplr=0.5,
        scale=0.5,
        close_mosaic=10,
        plots=True,
    )
    logger.info(f"Training done. Best weights: {results.save_dir}/weights/best.pt")
    logger.info(
        "To use this model in scene_analyzer set:\n"
        f"    config.YOLO_MODEL_PATH = '{results.save_dir}/weights/best.pt'"
    )


def _auto_run_name(args) -> str:
    parts = ["hazard_yolov8m"]
    if args.rgbd:
        parts.append(f"rgbd-{args.rgbd_init}")
    if args.distance_weighted:
        parts.append(f"distw-tau{args.tau:g}")
    if not args.rgbd and not args.distance_weighted:
        parts.append("baseline")
    return "_".join(parts)


if __name__ == "__main__":
    main()
